SolveRiddle: SolveRiddle.cpp EinsteinsRiddle.o 
	g++ -o SolveRiddle SolveRiddle.cpp EinsteinsRiddle.o

EinsteinsRiddle.o: EinsteinsRiddle.cpp
	g++ -c -o EinsteinsRiddle.o EinsteinsRiddle.cpp

clean:
	rm *.o SolveRiddle